### ISSUE TITLE
Possibility to redefine the Prompt String on the fly

### ISSUE THREAD

**Issue by sontags** [desertbit/grumble#1]
It would be rather nice to be able to rewrite the promt via func such as...
```
func SetPrompt(string) 
```
This would enable to provide some details about the current context as in...
```
dir > cd subdir
dir/subdir >
```

**Comment by sontags** [comment]
I found some very ugly workaround:

```
func setPrompt(p string) {
	App.Config().Prompt = fmt.Sprintf("%s > ", p)  // set Prompt
	App.SetPrintASCIILogo(func(a *grumble.App) {}) // make sure App.Run() does not do anything
	App.Run()                                      // call Run() to make sure prompt is set
}
```

**Comment by sontags** [comment]
Just figured out that this workaround cases all commands to be reinitiated and causes tab completion to have redundant output...

**Comment by sontags** [comment]
Bump...

If there is any interest in getting this implemented? If yes i could give it a try and send a pull request.

**Comment by r0l1** [comment]
Useful idea! I'll go over it soon. Thanks for the PR!

**Comment by r0l1** [comment]
Please shave a look at the [sample](https://github.com/desertbit/grumble/blob/250ec3108137eca7097a0c1dd9b19b2d635b741e/sample/full/cmd/prompt.go)

**Comment by sontags** [comment]
Hey, thanks there... Stuff is already adopted in my projects. Keep going!
