### ISSUE TITLE
Feature Request: Default Help Flag

### ISSUE THREAD

**Issue by LRTNZ** [desertbit/grumble#10]
Having been tinkering around with this tool, to create a utility program for a project I am working on, I was wondering if it would be possible to have the flag "--help" added across all commands, to bring up their individual help fields? 
Just as "Help command1 subcommand1" would bring up the help for subcommand1, could it be made so "command1 subcommand1 --help" would achieve the same, by default?

**Comment by skaldesh** [comment]
Yes, we can do that!

**Comment by LRTNZ** [comment]
Sweet! I have been caught out a few times with my own program, when I try to get my help info up with the "normal" --help flag in other shells.

**Comment by skaldesh** [comment]
Can you check out [this pull request](https://github.com/desertbit/grumble/pull/12)?

**Comment by LRTNZ** [comment]
That looks great! Thanks for that!

**Comment by r0l1** [comment]
Merged. Thanks!
