### ISSUE TITLE
Backtick (`) in input causes error

### ISSUE THREAD

**Issue by Matir** [desertbit/grumble#13]
When a backtick is the first rune of a word, shlex seems to choke on it.  If you run sample/simple:

```
go run .
foo » `ls`
error: invalid args: Unknown rune: 96
```

Might be a shlex bug, but there's no GitHub issues enabled there, so I decided to report it here.

**Comment by skaldesh** [comment]
Thanks! I'll look into it as well

**Comment by skaldesh** [comment]
Confirmed to be a shlex bug

**Comment by skaldesh** [comment]
Just found this library: https://github.com/anmitsu/go-shlex  
It seems to fix some bugs (handling non-ASCII correct, for example), I will test whether it is of help for us

**Comment by skaldesh** [comment]
It actually fixes the problems! Proper rune support, and backticks no longer an issue. Everything else seems to behave as before.
