### ISSUE TITLE
Improve Args parsing

### ISSUE THREAD

**Issue by skaldesh** [desertbit/grumble#3]
I would appreciate finer control over the allowed arguments of a command, similar to how flags are handled.  
I find myself do a lot checking for arguments in the Run methods of each command and converting the string arguments to the data types I actually need.

I'd suggest to do it very similar and replace "AllowArgs: bool" with a func(a *Args) {...}  
This new type Args would bundle all allowed arguments similar to the flags package, but of course just restrict the format for each argument.  
E.g. you could specify a String argument, optionally providing a regexp to check the format of it.  

What do you think of this? I'd happily do a PR for this!

**Comment by r0l1** [comment]
Sounds good. Could you post some code samples showing how an implementation would look like before and after the improvement?

**Comment by skaldesh** [comment]
yeah sure! Will do that as soon as I can!

**Comment by skaldesh** [comment]
Ok, I tried to include everything in one example:  
```
var regex = regexp.MustCompile("@|:")

&grumble.Command{
    Name: "test",
    Aliases: []string{"t"},
    Help: "only a test command",
    Usage: "test [OPTIONS] [USER@HOST:PORT] [ID]",
    AllowArgs: true,
    Run: func(c *grumble.Context) error {
        if len(c.Args) < 2 { 
            return errWrongNumberArgs 
        }
        pArgs := regex.Split(c.Args[0], -1)
        if len(pArgs) != 3 {
            return errInvalidFirstArgument
        }
        id, err := strconv.Atoi(c.Args[1])
        if err != nil {
            return errInvalidSecondArgument
        }
        // here the parsing part ends
        ...
    }
}
```  
Now, with argument parsing support:
```
&grumble.Command{
    Name: "test",
    Aliases: []string{"t"},
    Help: "only a test command",
    Args: func(a *grumble.Args) {
         a.StringRegex(0, "@|:", 3, "user@host:port")
         a.Uint(1, "id")
    },
    Run: func(c *grumble.Context) error {
        // no check for number of arguments, since we know that from the Args registration
        // we can directly access the splitted strings c.Args.StringRegex(0)[0|1|2]
        // no uint parsing, but c.Args.Uint(1)
    }
}
```
Notice also the missing `Usage` property. I think now that we know the arguments' structure, we could maybe build that automatically (but it can be of course overridden by providing a string nontheless).

**Comment by r0l1** [comment]
@skaldesh what's your current opinion about this?

**Comment by skaldesh** [comment]
Almost never using arguments tbh. Maybe not worth the hassle

**Comment by skaldesh** [comment]
In a current project, I am using arguments again pretty often and I do not like how it is now.  
Flags are so convenient to work with, I want the same for arguments...
