### ISSUE TITLE
App won't start up if short and long name of flag is the same

### ISSUE THREAD

**Issue by MikkelHJuul** [desertbit/grumble#32]
Startup panics with a pointer error. Needs error handling.  Like suggest leaving sort blank. 

Thanks for the great work

**Comment by skaldesh** [comment]
Hi!
I tried to reproduce what you describe with our simple sample:   
```go
App.AddCommand(&grumble.Command{
		Name:    "daemon",
		Help:    "run the daemon",
		Aliases: []string{"run"},
		Flags: func(f *grumble.Flags) {
			f.Duration("t", "t", time.Second, "timeout duration")
		},
		Args: func(a *grumble.Args) {
			// ...
		},
		Run: func(c *grumble.Context) error {
			c.App.Println("timeout:", c.Flags.Duration("t"))
			// ...
			return nil
		},
	})
```
Then: `go run ./sample/simple/main.go` leads to correct startup of the App  
When I run command daemon, it correctly prints its flags.  

Could you share a short code example that reproduces your issues? Thanks

**Comment by MikkelHJuul** [comment]
Ah, this is when you do it the other way around, so I guess that a more resilient solution would be an api-change where the short must ba a `rune`. I had a long: "to" and already used 't', so I put short to, 'to'.

I just chose not to add it

I just reran, and noticed that the app panics with a suitable message. so I'll just close this.

I totally missed it sorry.

**Comment by skaldesh** [comment]
no problem :) glad your issue is resolved
