### ISSUE TITLE
how do i delete a command？

### ISSUE THREAD

**Issue by sairson** [desertbit/grumble#40]
How do I delete a command?
To do this, I added a del function to the source code

`func (c *Commands)Del(name string) {
	for i,cmd := range c.list {
		if cmd.Name == name {
			c.list = append(c.list[:i],c.list[i+1:]...)
		}
	}
}
`

**Comment by skaldesh** [comment]
Hi  
Could you describe me the use case for this feature?

**Comment by sairson** [comment]
![image](https://user-images.githubusercontent.com/74412075/143962628-92a14839-163b-43f7-9d95-8a71ebae75a0.png)

I may need to hide or delete registered commands during execution, and I find that you do not have the removal function, which means that I can only keep registering commands, but cannot remove them

**Comment by sairson** [comment]
I have added a section to your source code that can be used to delete commands that have already been registered

![image](https://user-images.githubusercontent.com/74412075/143962959-d4b0672f-9d4d-4d0c-b4ee-a0d64c1c6c57.png)

**Comment by skaldesh** [comment]
I see. We have never needed something like that before. Would it be possible that instead of conditionally deleting a command, you conditionally add them?

**Comment by sairson** [comment]
But I think that having a function that deletes commands doesn't affect the program's functionality, and instead, it can be a helpful way for some people (like me). Of course it is possible to add a conditional command, but I find it more effective to remove a command because the program is required at some point

**Comment by r0l1** [comment]
Instead of deleting/adding commands, what do you think about following approach:

```go
grumble.Command{
    Name:      "daemon",
    Help:      "run the daemon",
    Aliases:   []string{"run"},

    Active: func() bool {
        // Executed to check the command active status.
        // ...
        return false;
    },
   // ...
}
```

**Comment by sairson** [comment]
I think this is a good approach, but adding a delete operation is not too much, because some people may have different requirements at the time of writing, and if you can add the above method, it is also easy to hide and reality the command line，thanks

**Comment by skaldesh** [comment]
We will add it!

**Comment by skaldesh** [comment]
remove command has been added
