### ISSUE TITLE
Add optional values to the flag field of the command command

### ISSUE THREAD

**Issue by sairson** [desertbit/grumble#46]
Grumble does not support adding subcommands to flag fields. For example, I want to complete a value of --flag on the command line
thanks

**Comment by skaldesh** [comment]
Do you have a small code sample for reproduction? Or you describe what to add to our samples to reproduce your problem :)

**Comment by sairson** [comment]
![image](https://user-images.githubusercontent.com/74412075/154915300-4d881bb5-6707-457b-99b4-7f10ba15ed8e.png)
I would like to add a completion field after flag as well

**Comment by skaldesh** [comment]
So I assume your flag should have some predefined values and you want completion for them?

**Comment by sairson** [comment]
yes

**Comment by sairson** [comment]
By the way, I just wanted to ask a simple question, does Grumble support grouping commands, sometimes, I might need to add a group of commands at the same time

**Comment by sairson** [comment]
yes，I want to know whether he has

**Comment by sairson** [comment]
Maybe I need is this, I need is a grouping of command, the command belongs to a group, I can at the same time on the set of commands to add and remove

**Comment by sairson** [comment]
![image](https://user-images.githubusercontent.com/74412075/160321403-88073bb7-5cc8-48ed-b906-63320402efb6.png)
I have used this library many times in my programming, and I think it is a very good CLI library. But every now and then I need a colleague to add and remove a set of commands, so I built the following set of commands based on yours。
