### ISSUE TITLE
Is there a way to retrieve the parameter list or flags list of a command?

### ISSUE THREAD

**Issue by meozky** [desertbit/grumble#61]
I am currently working on a real-time suggestion feature similar to redis-cli. Is there a way to retrieve the parameter list or flags list of a command?

**Comment by skaldesh** [comment]
If I understand you correctly, you want to retrieve the args and flags that have been registered on a command at runtime? That is currently not possible, as far as I am aware.

**Comment by meozky** [comment]
Yep, you've got it correctly and I'm looking for alternative approaches to resolve it
