### ISSUE TITLE
Support readline vi-mode

### ISSUE THREAD

**Issue by lewisthompson** [desertbit/grumble#8]
Could grumble app expose `readline`'s `SetVimMode` (https://github.com/chzyer/readline/blob/2972be24d48e78746da79ba8e24e8b488c9880de/example/readline-demo/readline-demo.go#L112-L125) such that implementing `set -o vi` in my app would be doable?

**Comment by r0l1** [comment]
Sounds like a great idea! If you provide a pull request, I am open to merge it :)

**Comment by skaldesh** [comment]
This issue is getting old now and with #15 (readline is no longer maintained), it is also no longer relevant
